[build]
buildCommand = "npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/api"
restartPolicyType = "on_failure"